#!/usr/bin/env bash
set -u

TASK_ID="task-037-roadmap-development-plan"
STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
PROJECT_ROOT="$(pwd)"
REPORT_DIR="${PROJECT_ROOT}/reports/${TASK_ID}"
BACKUP_DIR="${REPORT_DIR}/backup"
mkdir -p "${BACKUP_DIR}"
mkdir -p docs/roadmap

LOG_TXT="${REPORT_DIR}/log.txt"
REPORT_JSON="${REPORT_DIR}/report.json"
REPORT_MD="${REPORT_DIR}/report.md"

: > "${LOG_TXT}"

log() {
  echo "$1" | tee -a "${LOG_TXT}"
}

log "Task: ${TASK_ID}"
log "Started: ${STARTED_AT}"

EN_DOC="docs/roadmap/development-plan.en.md"
RU_DOC="docs/roadmap/development-plan.ru.md"

if [[ -f "${EN_DOC}" ]]; then
  cp "${EN_DOC}" "${BACKUP_DIR}/development-plan.en.md.bak" || true
  log "Backed up existing ${EN_DOC}"
fi

if [[ -f "${RU_DOC}" ]]; then
  cp "${RU_DOC}" "${BACKUP_DIR}/development-plan.ru.md.bak" || true
  log "Backed up existing ${RU_DOC}"
fi

log "Writing English roadmap for agents"

cat > "${EN_DOC}" <<'EN_DOC'
# Trading Terminal - Development Roadmap

Generated: 2026-07-23
Generated by: task-037-roadmap-development-plan
Audience: AI agents, orchestrator, backend, frontend, QA, DevOps
Source baseline: docs/agents/project-context.md

This document defines the high-level development plan for Trading Terminal.
AI agents must use this roadmap to propose the next safe task.
Do not skip stabilization blocks.
Do not start production trading.
Do not use secrets in code, logs, reports, or documentation.

---

## 1. Current Baseline

Project:
- Trading Terminal for MOEX analytics and algorithmic trading.
- Broker integration: T-Bank / Tinkoff Invest API.
- Mode: sandbox / development only.
- Production trading disabled.

Confirmed state:
- Branch: main.
- Backend: FastAPI application exists.
- Database: PostgreSQL schema trading exists.
- Analytics pipeline exists:
  - instruments;
  - candles_30min_raw;
  - candles_aggregated;
  - indicators;
  - signals;
  - top_stocks_by_volume.
- Signal generation produced 42275 signals.
- Signals exist for 30min, 1h, 4h.
- No 1d signals currently exist.
- 1d indicators are sparse: only 274 rows.
- Frontend source exists.
- Frontend dependencies were installed successfully.
- Frontend production build is not verified.
- Enhanced signals API features are not fully verified.

Important constraints:
- Use app.* imports, not src.*.
- Actual signal engine path is backend/app/analytics/signal_engine.py.
- Actual pattern base path is backend/app/analytics/patterns/base.py.
- backend/app/api/signals.py appears legacy and must be verified before use.
- Reports must be produced under reports/<task_id>/.
- Every task must produce report.json, report.md, log.txt.

---

## 2. Global Engineering Principles

1. Sandbox only.
   - No production trading.
   - No production tokens in tests.
   - No real order execution until risk controls exist.

2. Task-based development.
   - Every change is done through a task script.
   - Every task produces report.json.
   - The orchestrator reads report.json before proposing the next task.

3. Idempotency.
   - Data loading, aggregation, indicator calculation, signal generation, feature calculation, backtests, and model predictions must be repeatable.
   - Prefer delete-range plus insert, or upsert with unique constraints.

4. No future data leakage.
   - ML features and labels must use only past data.
   - Time-based splits only.
   - Add purge or embargo between train/validation/test windows.

5. Observability.
   - Every important operation must have logs, metrics, and artifacts.
   - Model training must store parameters, metrics, data window, git commit, and model artifact reference.

6. Safety.
   - Do not delete analytical tables without backup.
   - Do not modify trading.signals manually.
   - Do not commit .env, tokens, passwords, certificates.

---

## 3. High-Level Block Plan

Block A: Stabilization and API Readiness
Block B: Data Quality and Feature Store
Block C: Backtesting Engine
Block D: ML Feature and Label Framework
Block E: CatBoost and LightGBM Training
Block F: Prediction Service and Integration
Block G: Retraining and Monitoring
Block H: Risk, Orders and Terminal Schema
Block I: Observability and Governance

Recommended order:
A -> B -> C -> D -> E -> F -> G -> H -> I

Some blocks can run partially in parallel:
- Block C can start after Block A and part of Block B.
- Block D can start after Block B.
- Block H can start after Block F, but risk design can be drafted earlier.

---

## 4. Block A - Stabilization and API Readiness

Goal:
Make the current analytics and frontend baseline stable and verified.

Scope:
- Verify frontend production build.
- Verify frontend dev server.
- Verify backend health.
- Verify current API endpoints.
- Verify whether signals API supports:
  - pagination;
  - date filter;
  - sorting;
  - pattern_name;
  - figi;
  - stats endpoint.
- Fix missing API fields if required by frontend.
- Diagnose missing 1d signals.
- Commit approved documentation and scripts.

Suggested tasks:
- task-038-frontend-build-verify
- task-039-backend-api-verify
- task-040-signals-api-enhance
- task-041-daily-signals-diagnostics
- task-042-commit-docs-scripts

Acceptance criteria:
- npm run build succeeds.
- frontend dev server starts.
- backend /health returns ok.
- /api/signals returns items with pattern_name and figi.
- /api/signals supports limit, offset, date_from, date_to, sort_by, sort_dir.
- /api/signals/stats exists or is explicitly marked not implemented.
- 1d signal absence has a confirmed root cause.
- Documentation and scripts are committed or explicitly approved.

Risks:
- Frontend may expect API fields that backend does not return.
- Manual changes may not be committed.
- 1d data may be too sparse for current pattern logic.

---

## 5. Block B - Data Quality and Feature Store

Goal:
Create a reliable analytical data layer for backtesting and ML.

Scope:
- Validate instruments data.
- Validate candles_30min_raw completeness.
- Validate candles_aggregated consistency.
- Validate indicators correctness.
- Add data quality checks:
  - missing candles;
  - duplicate rows;
  - null OHLCV;
  - zero volume;
  - invalid timestamps;
  - ticker/figi mismatches;
  - timeframe gaps.
- Create feature store schema.
- Store normalized features for ML.
- Add data lineage metadata.

Suggested database objects:
- schema ml or analytics_ml;
- ml.features;
- ml.feature_sets;
- ml.data_quality_checks;
- ml.data_sources.

Feature examples:
- lag returns: 1, 2, 3, 5, 10, 20 bars;
- rolling volatility;
- rolling volume ratio;
- RSI, MACD, ATR, Bollinger features;
- SMA/EMA relationships;
- candle body and shadow ratios;
- time features: hour, weekday, month;
- ticker as categorical feature;
- timeframe as categorical feature;
- top stocks rank or liquidity bucket.

Acceptance criteria:
- Feature calculation is deterministic.
- Features are stored with ticker, timeframe, timestamp, feature_set, version.
- No future data is used.
- Data quality report exists.
- Critical data quality checks pass.

Risks:
- Feature leakage.
- Duplicate features.
- Inconsistent timezone handling.
- Different indicator versions.

---

## 6. Block C - Backtesting Engine

Goal:
Create a backtesting engine that can evaluate rule-based signals and ML predictions.

Scope:
- Historical replay using candles_aggregated.
- Support instruments from top_stocks_by_volume or custom universes.
- Support signal sources:
  - trading.signals;
  - ml.predictions;
  - future strategy signals.
- Simulate entries and exits.
- Support long-only first.
- Add optional short support later.
- Model transaction costs:
  - commission;
  - slippage;
  - spread approximation.
- Use MOEX-specific instrument data:
  - lot_size;
  - min_price_increment.
- Calculate equity curve.
- Calculate trades.
- Calculate metrics.

Suggested database objects:
- ml.backtest_runs;
- ml.backtest_trades;
- ml.backtest_positions;
- ml.backtest_equity;
- ml.backtest_metrics.

Metrics:
- total return;
- CAGR;
- Sharpe ratio;
- Sortino ratio;
- max drawdown;
- win rate;
- profit factor;
- average trade return;
- exposure;
- number of trades;
- turnover;
- cost impact.

Acceptance criteria:
- Backtest is deterministic.
- Backtest cannot use future candles.
- Backtest stores run parameters and git commit.
- Backtest can compare pattern signals and ML predictions.
- Backtest results are reproducible from report artifacts.

Risks:
- Look-ahead bias.
- Unrealistic fills.
- Ignoring lot sizes.
- Ignoring trading calendar.
- Overfitting to historical data.

---

## 7. Block D - ML Feature and Label Framework

Goal:
Prepare ML datasets with correct labels and time-based splits.

Scope:
- Define prediction horizons:
  - 1h;
  - 4h;
  - 1d.
- Define labels:
  - future return direction;
  - future return above cost threshold;
  - optional triple-barrier labels later.
- Define classes:
  - BUY;
  - SELL;
  - NO_TRADE.
- Create dataset snapshots.
- Create time-based splits:
  - train;
  - validation;
  - test.
- Add purge and embargo.
- Store dataset metadata.

Suggested database objects:
- ml.labels;
- ml.datasets;
- ml.dataset_splits;
- ml.label_definitions.

Label examples:
- next_1h_return;
- next_4h_return;
- next_1d_return;
- next_1h_return_after_costs;
- next_1d_direction;
- next_1d_class.

Acceptance criteria:
- Labels use only future price data relative to feature timestamp.
- Features and labels are joined by ticker, timeframe, timestamp.
- Train/validation/test splits are time-ordered.
- No test data appears in training.
- Dataset version is stored.

Risks:
- Label leakage.
- Imbalanced classes.
- Too few positive examples.
- Horizon mismatch between features and labels.

---

## 8. Block E - CatBoost and LightGBM Training

Goal:
Add CatBoost and LightGBM model training pipelines.

Scope:
- Add optional ML dependencies:
  - catboost;
  - lightgbm;
  - scikit-learn;
  - shap;
  - joblib.
- Create training scripts.
- Support models:
  - CatBoostClassifier;
  - LGBMClassifier.
- Support categorical features:
  - ticker;
  - timeframe;
  - hour;
  - weekday;
  - liquidity bucket.
- Store experiments.
- Store model artifacts.
- Store metrics.
- Support hyperparameter search.
- Support champion/challenger comparison.

Suggested database objects:
- ml.experiments;
- ml.models;
- ml.model_metrics;
- ml.model_artifacts.

Model metadata:
- model_id;
- model_type;
- feature_set_version;
- dataset_version;
- label_definition;
- horizon;
- params;
- metrics;
- git_commit;
- created_at;
- status: candidate, champion, archived.

Metrics:
- accuracy;
- precision;
- recall;
- f1;
- roc_auc;
- pr_auc;
- logloss;
- calibration error;
- top quantile precision;
- feature importance.

Acceptance criteria:
- Training is reproducible.
- Model artifact can be loaded.
- Model can predict on new features.
- Metrics are stored per dataset split.
- Champion model is selected by validation and backtest criteria.
- CatBoost and LightGBM can be compared.

Risks:
- Overfitting.
- Data leakage.
- Model size too large.
- Inconsistent feature order.
- Categorical feature misuse.

---

## 9. Block F - Prediction Service and Integration

Goal:
Use trained models to generate predictions and integrate them into the terminal.

Scope:
- Batch prediction pipeline.
- Predict for top stocks or custom universe.
- Store predictions in ml.predictions.
- Expose API endpoints:
  - GET /api/ml/models;
  - GET /api/ml/predictions;
  - POST /api/ml/predict;
  - GET /api/backtests;
  - GET /api/backtests/<id>/metrics.
- Add frontend pages:
  - Models;
  - Predictions;
  - Backtests;
  - Model detail.
- Compare ML predictions with rule-based signals.

Suggested database objects:
- ml.predictions;
- ml.prediction_runs.

Prediction fields:
- ticker;
- figi;
- timeframe;
- timestamp;
- model_id;
- horizon;
- predicted_class;
- probability_buy;
- probability_sell;
- probability_no_trade;
- expected_return;
- confidence;
- features_version;
- created_at.

Acceptance criteria:
- Predictions are deterministic for a fixed model and feature snapshot.
- Predictions do not use future data.
- API returns model metadata and prediction explanation.
- Frontend can display predictions and backtest metrics.
- ML predictions can be backtested.

Risks:
- Serving stale features.
- Model version mismatch.
- Feature schema drift.
- Prediction leakage into training.

---

## 10. Block G - Retraining and Monitoring

Goal:
Support safe retraining and model quality monitoring.

Scope:
- Scheduled retraining:
  - daily;
  - weekly;
  - rolling window.
- Champion/challenger workflow.
- Automatic validation gates.
- Model promotion only if metrics pass thresholds.
- Data drift monitoring.
- Prediction drift monitoring.
- Performance decay monitoring.
- Backtest live divergence monitoring.

Suggested database objects:
- ml.monitoring_metrics;
- ml.retraining_jobs;
- ml.model_promotions.

Monitoring metrics:
- feature distribution drift;
- prediction distribution drift;
- label rate drift;
- precision decay;
- roc_auc decay;
- backtest vs live divergence;
- data freshness.

Acceptance criteria:
- Retraining creates a new model candidate.
- Candidate is validated before promotion.
- Old champion can be restored.
- Monitoring dashboard or API exists.
- Alerts are generated for critical drift.

Risks:
- Automatic promotion of overfitted model.
- Concept drift.
- Data quality degradation.
- Retraining on corrupted data.

---

## 11. Block H - Risk, Orders and Terminal Schema

Goal:
Prepare the operational part of the terminal with strict risk controls.

Scope:
- Create schema terminal.
- Design entities:
  - accounts;
  - broker_connections;
  - orders;
  - order_executions;
  - positions;
  - portfolio_snapshots;
  - risk_limits;
  - risk_checks;
  - trading_controls;
  - audit_logs.
- Implement order preview.
- Implement risk checks.
- Implement human confirmation requirement.
- Keep real order execution disabled by default.
- Add kill switch.

Risk controls:
- max order amount;
- max daily loss;
- max open orders;
- max orders per minute;
- max position size;
- instrument blacklist;
- market orders disabled by default;
- margin trading disabled by default;
- trading enabled flag.

Acceptance criteria:
- No order can bypass risk checks.
- Every order action is audited.
- Human confirmation is required before submission.
- Kill switch stops all new orders.
- Production trading remains disabled until explicitly approved.

Risks:
- Accidental real trading.
- Missing audit trail.
- Incorrect risk limits.
- Broker API errors not handled.

---

## 12. Block I - Observability and Governance

Goal:
Make the system observable, auditable, and maintainable.

Scope:
- Structured logging.
- Metrics endpoint.
- Prometheus metrics.
- Grafana dashboards.
- Alerting.
- Task report dashboard.
- Model experiment dashboard.
- Documentation updates.
- Security review.
- Backup and restore procedures.

Possible metrics:
- backend health;
- DB latency;
- data freshness;
- signal generation duration;
- model training duration;
- prediction latency;
- backtest duration;
- error rate;
- drift metrics.

Acceptance criteria:
- Critical failures are visible.
- Data freshness is monitored.
- Model metrics are visible.
- Reports are easy to locate.
- Secrets are not exposed.

Risks:
- Too many metrics.
- Missing alerts.
- Sensitive data in logs.

---

## 13. Agent Decision Rules

For orchestrator and autonomous agents:

1. Always read the latest report.json before proposing a task.
2. If Block A is not complete, prefer stabilization tasks.
3. Do not start model training before feature store and label framework exist.
4. Do not start prediction serving before backtesting validates the model.
5. Do not enable order execution before Block H risk controls exist.
6. If data is unknown, propose a read-only discovery task.
7. If a task fails, propose a fix task with the same task family.
8. Never propose commands that print secrets.
9. Never propose destructive database operations without backup.
10. Prefer small, verifiable tasks over large risky changes.

---

## 14. Recommended Task Sequence

Phase 1: Stabilization
- task-038-frontend-build-verify
- task-039-backend-api-verify
- task-040-signals-api-enhance
- task-041-daily-signals-diagnostics
- task-042-commit-docs-scripts

Phase 2: Data and Features
- task-043-data-quality-checks
- task-044-ml-schema
- task-045-feature-store
- task-046-feature-validation

Phase 3: Backtesting
- task-047-backtest-engine-core
- task-048-backtest-metrics
- task-049-backtest-api
- task-050-backtest-frontend

Phase 4: ML Training
- task-051-label-framework
- task-052-dataset-splitter
- task-053-catboost-trainer
- task-054-lightgbm-trainer
- task-055-model-registry

Phase 5: Prediction and Retraining
- task-056-prediction-pipeline
- task-057-prediction-api
- task-058-retraining-pipeline
- task-059-monitoring-metrics

Phase 6: Terminal and Risk
- task-060-terminal-schema
- task-061-risk-limits
- task-062-order-preview
- task-063-audit-logs

---

## 15. Machine-Readable Summary

roadmap_version: 1
project: trading-terminal
environment: sandbox
production_trading: false
current_branch: main
analytics_schema: trading
future_schemas: ml, terminal
blocks:
  - A: stabilization_and_api_readiness
  - B: data_quality_and_feature_store
  - C: backtesting_engine
  - D: ml_feature_and_label_framework
  - E: catboost_lightgbm_training
  - F: prediction_service_and_integration
  - G: retraining_and_monitoring
  - H: risk_orders_terminal_schema
  - I: observability_and_governance
next_priority: Block A
EN_DOC

log "Writing Russian roadmap for human"

cat > "${RU_DOC}" <<'RU_DOC'
# Trading Terminal - План развития

Сформировано: 2026-07-23
Сформировано задачей: task-037-roadmap-development-plan
Назначение: дорожная карта развития проекта для человека
Исходный контекст: docs/agents/project-context.md

Этот документ описывает развитие проекта крупными блоками.
Он включает backtest-инструменты, подключение CatBoost и LightGBM, обучение, переобучение и прогнозирование.

---

## 1. Текущее состояние

Проект:
- аналитический терминал для MOEX;
- интеграция с T-Bank / Tinkoff Invest API;
- режим: sandbox / разработка;
- production-торговля отключена.

Подтверждённое состояние:
- ветка: main;
- backend на FastAPI существует;
- PostgreSQL схема trading существует;
- pipeline аналитики существует:
  - инструменты;
  - 30-минутные свечи;
  - агрегированные свечи;
  - индикаторы;
  - сигналы;
  - ТОП-акции по объёму;
- сгенерировано 42275 сигналов;
- сигналы есть для 30min, 1h, 4h;
- 1d сигналов пока нет;
- 1d индикаторов мало: 274 строки;
- frontend исходники есть;
- npm зависимости устанавливались успешно;
- production build frontend ещё не проверен;
- расширенный signals API проверен не полностью.

Важно:
- использовать импорты app.*, а не src.*;
- signal engine находится в backend/app/analytics/signal_engine.py;
- base паттернов находится в backend/app/analytics/patterns/base.py;
- backend/app/api/signals.py похож на legacy и требует проверки;
- все задачи должны создавать отчёты в reports/<task_id>/.

---

## 2. Общие принципы

1. Только sandbox.
   - Никакой production-торговли.
   - Никаких production-токенов в тестах.
   - Реальные заявки только после отдельного риск-блока и явного разрешения.

2. Разработка через задачи.
   - Каждое изменение делается через task-скрипт.
   - Каждая задача создаёт report.json.
   - Оркестратор читает report.json перед следующим шагом.

3. Идемпотентность.
   - Загрузку данных, агрегацию, индикаторы, сигналы, фичи, backtest и прогнозы можно безопасно повторять.
   - Лучше использовать удаление диапазона и вставку или upsert.

4. Запрет утечки будущих данных.
   - ML-фичи и лейблы используют только прошлые данные.
   - Разделение данных только по времени.
   - Между train/validation/test нужен purge или embargo.

5. Наблюдаемость.
   - Важные операции имеют логи, метрики и артефакты.
   - Обучение моделей сохраняет параметры, метрики, окно данных, git commit и ссылку на модель.

6. Безопасность.
   - Не удалять аналитические таблицы без backup.
   - Не менять trading.signals вручную.
   - Не коммитить .env, токены, пароли, сертификаты.

---

## 3. Крупные блоки развития

Блок A: Стабилизация и готовность API
Блок B: Качество данных и feature store
Блок C: Backtesting engine
Блок D: ML-фичи и лейблы
Блок E: Обучение CatBoost и LightGBM
Блок F: Сервис прогнозов и интеграция
Блок G: Переобучение и мониторинг
Блок H: Риск, заявки и схема terminal
Блок I: Наблюдаемость и управление

Рекомендуемая последовательность:
A -> B -> C -> D -> E -> F -> G -> H -> I

Можно частично параллелить:
- Block C можно начинать после Block A и части Block B.
- Block D можно начинать после Block B.
- Block H можно проектировать раньше, но реализовывать после Block F.

---

## 4. Блок A - Стабилизация и готовность API

Цель:
Сделать текущий backend, frontend и API стабильными и проверенными.

Что входит:
- проверить npm run build;
- проверить frontend dev server;
- проверить backend /health;
- проверить текущие API endpoints;
- проверить, что /api/signals поддерживает:
  - пагинацию;
  - фильтр по дате;
  - сортировку;
  - pattern_name;
  - figi;
  - статистику;
- при необходимости доработать API;
- диагностировать отсутствие 1d сигналов;
- закоммитить документацию и скрипты.

Примеры задач:
- task-038-frontend-build-verify
- task-039-backend-api-verify
- task-040-signals-api-enhance
- task-041-daily-signals-diagnostics
- task-042-commit-docs-scripts

Критерии готовности:
- npm run build проходит;
- frontend запускается;
- backend отвечает /health;
- /api/signals возвращает pattern_name и figi;
- /api/signals поддерживает limit, offset, date_from, date_to, sort_by, sort_dir;
- есть /api/signals/stats или явно зафиксировано, что его ещё нет;
- причина отсутствия 1d сигналов понятна.

Риски:
- frontend ждёт поля, которых нет в API;
- ручные изменения не закоммичены;
- для 1d недостаточно истории.

---

## 5. Блок B - Качество данных и feature store

Цель:
Подготовить надёжный слой данных для backtest и ML.

Что входит:
- проверка инструментов;
- проверка 30-минутных свечей;
- проверка агрегированных свечей;
- проверка индикаторов;
- проверки качества данных:
  - пропуски свечей;
  - дубликаты;
  - null OHLCV;
  - нулевые объёмы;
  - некорректные timestamp;
  - расхождения ticker/figi;
  - разрывы таймфреймов;
- создание схемы для ML;
- хранение нормализованных фичей;
- версионирование feature set.

Примеры объектов БД:
- schema ml;
- ml.features;
- ml.feature_sets;
- ml.data_quality_checks;
- ml.data_sources.

Примеры фичей:
- lag returns: 1, 2, 3, 5, 10, 20 баров;
- rolling volatility;
- volume ratio;
- RSI, MACD, ATR, Bollinger;
- отношения SMA/EMA;
- тело свечи и тени;
- hour, weekday, month;
- ticker как категориальная фича;
- timeframe как категориальная фича;
- ликвидность или rank из top_stocks_by_volume.

Критерии готовности:
- расчёт фичей детерминирован;
- фичи хранятся с ticker, timeframe, timestamp, feature_set, version;
- нет утечки будущих данных;
- есть отчёт о качестве данных.

Риски:
- leakage;
- дубликаты фичей;
- несогласованные таймзоны;
- разные версии индикаторов.

---

## 6. Блок C - Backtesting engine

Цель:
Создать движок backtest для проверки правил и ML-прогнозов.

Что входит:
- исторический прогон по candles_aggregated;
- поддержка universe:
  - top_stocks_by_volume;
  - ручной список;
- источники сигналов:
  - trading.signals;
  - ml.predictions;
  - будущие стратегии;
- симуляция входов и выходов;
- сначала long-only;
- позже можно short;
- комиссия;
- slippage;
- spread approximation;
- учёт lot_size;
- учёт min_price_increment;
- equity curve;
- сделки;
- метрики.

Примеры объектов БД:
- ml.backtest_runs;
- ml.backtest_trades;
- ml.backtest_positions;
- ml.backtest_equity;
- ml.backtest_metrics.

Метрики:
- total return;
- CAGR;
- Sharpe;
- Sortino;
- max drawdown;
- win rate;
- profit factor;
- average trade return;
- exposure;
- number of trades;
- turnover;
- cost impact.

Критерии готовности:
- backtest детерминирован;
- backtest не использует будущие свечи;
- backtest сохраняет параметры и git commit;
- можно сравнить паттерны и ML;
- результаты воспроизводимы.

Риски:
- look-ahead bias;
- нереалистичные исполнения;
- игнорирование лотов;
- игнорирование торгового календаря;
- переобучение под историю.

---

## 7. Блок D - ML-фичи и лейблы

Цель:
Подготовить ML-датасеты с правильными целевыми переменными.

Что входит:
- горизонты:
  - 1h;
  - 4h;
  - 1d;
- лейблы:
  - направление будущего движения;
  - доходность выше порога с учётом затрат;
  - позже triple-barrier;
- классы:
  - BUY;
  - SELL;
  - NO_TRADE;
- датасеты;
- train/validation/test;
- purge и embargo;
- версионирование датасетов.

Примеры объектов БД:
- ml.labels;
- ml.datasets;
- ml.dataset_splits;
- ml.label_definitions.

Примеры лейблов:
- next_1h_return;
- next_4h_return;
- next_1d_return;
- next_1h_return_after_costs;
- next_1d_direction;
- next_1d_class.

Критерии готовности:
- лейблы используют только будущую цену относительно timestamp фичей;
- фичи и лейблы соединяются по ticker, timeframe, timestamp;
- split по времени;
- test не попадает в train;
- версия датасета сохраняется.

Риски:
- label leakage;
- дисбаланс классов;
- мало положительных примеров;
- несоответствие горизонта фичей и лейбла.

---

## 8. Блок E - Обучение CatBoost и LightGBM

Цель:
Добавить обучение моделей CatBoost и LightGBM.

Что входит:
- ML-зависимости:
  - catboost;
  - lightgbm;
  - scikit-learn;
  - shap;
  - joblib;
- скрипты обучения;
- CatBoostClassifier;
- LGBMClassifier;
- категориальные фичи:
  - ticker;
  - timeframe;
  - hour;
  - weekday;
  - liquidity bucket;
- эксперименты;
- артефакты моделей;
- метрики;
- hyperparameter search;
- champion/challenger.

Примеры объектов БД:
- ml.experiments;
- ml.models;
- ml.model_metrics;
- ml.model_artifacts.

Метаданные модели:
- model_id;
- model_type;
- feature_set_version;
- dataset_version;
- label_definition;
- horizon;
- params;
- metrics;
- git_commit;
- created_at;
- status: candidate, champion, archived.

Метрики:
- accuracy;
- precision;
- recall;
- f1;
- roc_auc;
- pr_auc;
- logloss;
- calibration error;
- top quantile precision;
- feature importance.

Критерии готовности:
- обучение воспроизводимо;
- модель можно загрузить;
- модель умеет predict;
- метрики сохранены по split;
- champion выбирается по validation и backtest;
- CatBoost и LightGBM можно сравнить.

Риски:
- переобучение;
- leakage;
- большой размер модели;
- неправильный порядок фичей;
- неправильная работа с категориальными фичами.

---

## 9. Блок F - Сервис прогнозов и интеграция

Цель:
Использовать обученные модели для прогнозов и показать их в терминале.

Что входит:
- batch prediction pipeline;
- прогнозы для top stocks или universe;
- хранение прогнозов в ml.predictions;
- API:
  - GET /api/ml/models;
  - GET /api/ml/predictions;
  - POST /api/ml/predict;
  - GET /api/backtests;
  - GET /api/backtests/<id>/metrics;
- frontend страницы:
  - Models;
  - Predictions;
  - Backtests;
  - Model detail;
- сравнение ML-прогнозов и rule-based сигналов.

Примеры объектов БД:
- ml.predictions;
- ml.prediction_runs.

Поля прогноза:
- ticker;
- figi;
- timeframe;
- timestamp;
- model_id;
- horizon;
- predicted_class;
- probability_buy;
- probability_sell;
- probability_no_trade;
- expected_return;
- confidence;
- features_version;
- created_at.

Критерии готовности:
- прогнозы детерминированы для фиксированной модели и snapshot фичей;
- прогнозы не используют будущие данные;
- API возвращает метаданные модели;
- frontend показывает прогнозы и метрики;
- ML-прогнозы можно прогнать через backtest.

Риски:
- устаревшие фичи;
- несовпадение версии модели;
- drift схемы фичей;
- попадание прогнозов в обучение.

---

## 10. Блок G - Переобучение и мониторинг

Цель:
Обеспечить безопасное переобучение и контроль качества моделей.

Что входит:
- расписание переобучения:
  - daily;
  - weekly;
  - rolling window;
- champion/challenger;
- validation gates;
- promotion только при прохождении порогов;
- data drift;
- prediction drift;
- performance decay;
- расхождение backtest и live.

Примеры объектов БД:
- ml.monitoring_metrics;
- ml.retraining_jobs;
- ml.model_promotions.

Метрики мониторинга:
- drift распределения фичей;
- drift распределения прогнозов;
- drift частоты лейблов;
- падение precision;
- падение roc_auc;
- расхождение backtest/live;
- свежесть данных.

Критерии готовности:
- переобучение создаёт нового кандидата;
- кандидат проверяется перед promotion;
- старый champion можно восстановить;
- есть мониторинг;
- есть алерты на критический drift.

Риски:
- автоматический promotion переобученной модели;
- concept drift;
- ухудшение качества данных;
- обучение на битых данных.

---

## 11. Блок H - Риск, заявки и схема terminal

Цель:
Подготовить операционную часть терминала с жёстким контролем риска.

Что входит:
- схема terminal;
- сущности:
  - accounts;
  - broker_connections;
  - orders;
  - order_executions;
  - positions;
  - portfolio_snapshots;
  - risk_limits;
  - risk_checks;
  - trading_controls;
  - audit_logs;
- order preview;
- risk checks;
- human confirmation;
- real execution по умолчанию выключен;
- kill switch.

Риск-лимиты:
- max order amount;
- max daily loss;
- max open orders;
- max orders per minute;
- max position size;
- instrument blacklist;
- market orders disabled by default;
- margin trading disabled by default;
- trading enabled flag.

Критерии готовности:
- заявка не может обойти risk checks;
- каждое действие пишется в audit;
- нужно подтверждение человека;
- kill switch останавливает новые заявки;
- production trading выключен до явного разрешения.

Риски:
- случайная реальная торговля;
- отсутствие audit trail;
- неправильные лимиты;
- необработанные ошибки брокера.

---

## 12. Блок I - Наблюдаемость и управление

Цель:
Сделать систему наблюдаемой, аудируемой и сопровождаемой.

Что входит:
- структурированные логи;
- metrics endpoint;
- Prometheus;
- Grafana;
- алерты;
- dashboard по task-отчётам;
- dashboard по моделям;
- обновление документации;
- security review;
- backup и restore.

Возможные метрики:
- backend health;
- DB latency;
- свежесть данных;
- длительность генерации сигналов;
- длительность обучения;
- latency прогнозов;
- длительность backtest;
- error rate;
- drift metrics.

Критерии готовности:
- критические ошибки видны;
- свежесть данных контролируется;
- метрики моделей видны;
- отчёты легко найти;
- секреты не попадают в логи.

Риски:
- слишком много метрик;
- отсутствие алертов;
- чувствительные данные в логах.

---

## 13. Рекомендуемая последовательность задач

Фаза 1: Стабилизация
- task-038-frontend-build-verify
- task-039-backend-api-verify
- task-040-signals-api-enhance
- task-041-daily-signals-diagnostics
- task-042-commit-docs-scripts

Фаза 2: Данные и фичи
- task-043-data-quality-checks
- task-044-ml-schema
- task-045-feature-store
- task-046-feature-validation

Фаза 3: Backtesting
- task-047-backtest-engine-core
- task-048-backtest-metrics
- task-049-backtest-api
- task-050-backtest-frontend

Фаза 4: ML
- task-051-label-framework
- task-052-dataset-splitter
- task-053-catboost-trainer
- task-054-lightgbm-trainer
- task-055-model-registry

Фаза 5: Прогнозы и переобучение
- task-056-prediction-pipeline
- task-057-prediction-api
- task-058-retraining-pipeline
- task-059-monitoring-metrics

Фаза 6: Terminal и риск
- task-060-terminal-schema
- task-061-risk-limits
- task-062-order-preview
- task-063-audit-logs

---

## 14. Краткая сводка

Версия плана: 1
Проект: trading-terminal
Режим: sandbox
Production trading: false
Текущая ветка: main
Аналитическая схема: trading
Будущие схемы: ml, terminal
Следующий приоритет: Block A - стабилизация и готовность API
RU_DOC

FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "${REPORT_JSON}" <<JSON
{
  "task_id": "${TASK_ID}",
  "status": "success",
  "stage": "roadmap_docs_created",
  "started_at": "${STARTED_AT}",
  "finished_at": "${FINISHED_AT}",
  "docs": [
    "${EN_DOC}",
    "${RU_DOC}"
  ],
  "next_action": "Review docs/roadmap/development-plan.en.md and docs/roadmap/development-plan.ru.md, then start Block A with task-038-frontend-build-verify"
}
JSON

cat > "${REPORT_MD}" <<MD
# ${TASK_ID}

Status: success
Stage: roadmap_docs_created
Started: ${STARTED_AT}
Finished: ${FINISHED_AT}

Created docs:

- ${EN_DOC}
- ${RU_DOC}

Next action:

Review the roadmap documents, then start Block A with task-038-frontend-build-verify.
MD

log "English doc: ${EN_DOC}"
log "Russian doc: ${RU_DOC}"
log "Report JSON: ${REPORT_JSON}"
log "Done"

exit 0
