#!/usr/bin/env bash
set -u

TASK_ID="task-036-docs-project-context"
STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
PROJECT_ROOT="$(pwd)"
REPORT_DIR="${PROJECT_ROOT}/reports/${TASK_ID}"
BACKUP_DIR="${REPORT_DIR}/backup"
mkdir -p "${BACKUP_DIR}"
mkdir -p docs/agents

LOG_TXT="${REPORT_DIR}/log.txt"
REPORT_JSON="${REPORT_DIR}/report.json"
REPORT_MD="${REPORT_DIR}/report.md"

: > "${LOG_TXT}"

log() {
  echo "$1" | tee -a "${LOG_TXT}"
}

log "Task: ${TASK_ID}"
log "Started: ${STARTED_AT}"

EN_DOC="docs/agents/project-context.md"
RU_DOC="docs/project-context.ru.md"

if [[ -f "${EN_DOC}" ]]; then
  cp "${EN_DOC}" "${BACKUP_DIR}/project-context.md.bak" || true
  log "Backed up existing ${EN_DOC}"
fi

if [[ -f "${RU_DOC}" ]]; then
  cp "${RU_DOC}" "${BACKUP_DIR}/project-context.ru.md.bak" || true
  log "Backed up existing ${RU_DOC}"
fi

log "Writing English agent documentation"

cat > "${EN_DOC}" <<'EN_DOC'
# Trading Terminal - Agent Project Context

Generated: 2026-07-23
Generated by: task-036-docs-project-context
Source artifacts:
- reports/task-035a-project-db-scan-fix/file_scan_report.md
- reports/task-035a-project-db-scan-fix/db_schema.md
- reports/task-035a-project-db-scan-fix/current_tree.txt

This document is a verified baseline for AI agents.
If a fact is not present here, verify it before acting.

---

## 1. Project Summary

Trading Terminal is an AI-assisted analytics and algorithmic trading platform for MOEX.

Broker integration:
- T-Bank / Tinkoff Invest API
- t-tech-investments SDK
- sandbox / development mode only

Current phase:
- market data collection;
- candle aggregation;
- indicator calculation;
- signal generation;
- frontend visualization;
- trading execution is not enabled.

Production trading is disabled.

---

## 2. Repository State

Branch:
- main

Git status observed in current_tree.txt:
- modified: agents/orchestrator/prompt.md
- untracked: scripts/db_schema_scanner.py
- untracked: scripts/task-034-project-rescan.sh
- untracked: scripts/task-035-project-db-scan.sh
- untracked: scripts/task-035a-project-db-scan-fix.sh

File scan summary:
- total selected files: 142
- Python files: 43
- Markdown files: 8
- shell scripts: 68
- frontend files: TS, TSX, JS, CSS, HTML, JSON
- YAML config files: 2

Python metrics:
- total Python lines: 6460
- classes: 29
- top-level functions: 77
- methods: 77
- imports: 164

---

## 3. Technology Stack

Backend:
- Python 3.12
- FastAPI
- uvicorn
- psycopg2-binary
- pandas
- asyncpg
- pydantic
- PyYAML

Frontend:
- React 18
- TypeScript
- Vite
- Tailwind CSS
- lightweight-charts

Database:
- PostgreSQL
- analytics schema: trading
- future operations schema: terminal

Infrastructure:
- Docker Compose
- backend service
- agent service
- external PostgreSQL access from Docker via host.docker.internal

Agent stack:
- Ollama
- qwen2.5-coder:7b
- config/agents.yaml

---

## 4. High-Level Architecture

Main components:

1. Backend API
   - FastAPI application
   - read-only market data endpoints
   - health endpoint

2. Analytics Pipeline
   - instruments loading
   - 30-minute candle loading
   - candle aggregation
   - indicator calculation
   - signal generation

3. Database
   - PostgreSQL schema trading
   - candles, indicators, signals, instruments, top stocks

4. Frontend
   - React app
   - signals table
   - pattern statistics
   - top stocks
   - instruments
   - signal detail modal with candle chart

5. Agent System
   - orchestrator
   - devops executor
   - task-based development protocol

---

## 5. Directory Map

Authoritative source:
- reports/task-035a-project-db-scan-fix/current_tree.txt

Key paths:

Backend:
- backend/app/main.py
- backend/app/api/market_data.py
- backend/app/api/signals.py
- backend/app/analytics/indicators_manager.py
- backend/app/analytics/signal_engine.py
- backend/app/analytics/signal_generator.py
- backend/app/analytics/run_generate_signals.py
- backend/app/analytics/aggregate_candles.py
- backend/app/analytics/candles_aggregator.py
- backend/app/analytics/pipeline.py
- backend/app/analytics/top_stocks.py
- backend/app/analytics/patterns/base.py
- backend/app/analytics/patterns/trend.py
- backend/app/analytics/patterns/mean_reversion.py
- backend/app/analytics/patterns/breakout.py
- backend/app/analytics/patterns/volume.py
- backend/app/analytics/patterns/price_action.py
- backend/app/broker/data_loader.py
- backend/app/core/config_manager.py
- backend/app/db/db_manager.py
- backend/tests/

Frontend:
- frontend/package.json
- frontend/vite.config.js
- frontend/tsconfig.json
- frontend/tailwind.config.js
- frontend/postcss.config.js
- frontend/index.html
- frontend/src/main.tsx
- frontend/src/App.tsx
- frontend/src/api.ts
- frontend/src/types.ts
- frontend/src/components/SignalsPanel.tsx
- frontend/src/components/PatternStatsPanel.tsx
- frontend/src/components/SignalDetailModal.tsx
- frontend/src/components/CandleChart.tsx
- frontend/src/components/TopStocksPanel.tsx
- frontend/src/components/InstrumentsPanel.tsx

Docs:
- docs/agent-protocol.md
- docs/architecture/database.md
- docs/architecture/overview.md
- docs/domain/data-model.md
- docs/product/mvp.md
- docs/security/secrets.md
- docs/orchestrator/first-task.md

Config:
- config/agents.yaml
- .env.example

Scripts:
- scripts/task-*.sh
- scripts/targeted_project_scanner.py
- scripts/db_schema_scanner.py

---

## 6. Backend Notes

Application entrypoint:
- backend/app/main.py

Known registered routes from baseline code:
- /health
- /api/instruments
- /api/candles
- /api/signals
- /api/top-stocks-by-volume

Important:
- backend/app/api/signals.py exists but appears to be a legacy router.
- current baseline main.py registers market_data routes.
- verify backend/app/api/signals.py before enabling or modifying it.

DB access:
- backend/app/db/db_manager.py provides synchronous DBManager.
- DBManager is intended for analytics, ETL and utility workloads.
- FastAPI request handlers currently use synchronous DB access through market_data.py.
- asyncpg exists in requirements and backend/app/db/check_external.py, but main API flow is not fully async yet.

Configuration:
- backend/app/core/config_manager.py loads settings from environment and YAML.
- database password must come only from environment variables.
- environment variables include:
  - TINVEST_TOKEN
  - TINVEST_ACC
  - PSTGRS_PWD
  - POSTGRES_HOST
  - POSTGRES_PORT
  - POSTGRES_USER
  - POSTGRES_DB
  - MARKET_DATA_DATABASE_URL
  - MARKET_DATA_SCHEMA

---

## 7. Analytics Pipeline

Logical data flow:

instruments
  -> candles_30min_raw
    -> candles_aggregated
      -> indicators
        -> signals

Top stocks flow:

candles / instruments
  -> top_stocks_by_volume

Signal generation flow:

indicators
  -> SignalEngine
    -> patterns
      -> trading.signals

Pattern files:
- backend/app/analytics/patterns/base.py
- backend/app/analytics/patterns/trend.py
- backend/app/analytics/patterns/mean_reversion.py
- backend/app/analytics/patterns/breakout.py
- backend/app/analytics/patterns/volume.py
- backend/app/analytics/patterns/price_action.py

Pattern engine:
- backend/app/analytics/signal_engine.py

Signal generator:
- backend/app/analytics/signal_generator.py

Known pattern names:
- Trend_SMA_Alignment
- MR_RSI_Reversal
- BO_BB_Squeeze
- VOL_Spike
- VOL_Low_Pullback
- PA_Hammer
- PA_HangingMan
- PA_Engulfing
- PA_ThreeWhiteSoldiers
- PA_ThreeBlackCrows

Important scanner correction:
- file_scan_report.md lists missing important files:
  - backend/app/analytics/signal_patterns/engine.py
  - backend/app/analytics/signal_patterns/base.py
- actual project paths are:
  - backend/app/analytics/signal_engine.py
  - backend/app/analytics/patterns/base.py
- do not create signal_patterns/engine.py or signal_patterns/base.py unless intentionally refactoring module layout.

---

## 8. Database Model: schema trading

Scan time:
- 2026-07-23T08:59:15

Schema:
- trading

Tables:

| Table | Rows | Columns | Purpose |
|---|---:|---:|---|
| candles | 3326 | 10 | legacy / interval candles, monthly samples observed |
| candles_30min_raw | 27960 | 9 | source 30-minute candles |
| candles_aggregated | 71195 | 10 | aggregated candles by timeframe |
| indicators | 58784 | 33 | calculated technical indicators |
| instruments | 4272 | 15 | instrument directory |
| signals | 42275 | 19 | generated trading signals |
| signals_backup_task_031e | 6648 | 19 | backup table, not used by application |
| top_stocks_by_volume | 30 | 12 | top stocks by volume |

---

## 9. Candle Aggregation State

candles_aggregated rows by timeframe:

| Timeframe | Rows |
|---|---:|
| 30min | 35339 |
| 1h | 18769 |
| 2h | 8571 |
| 4h | 6008 |
| 1d | 1946 |
| 1w | 389 |
| 1M | 173 |

Observation:
- 2h candles exist in candles_aggregated.
- current signal generation baseline used 30min, 1h, 4h, 1d.
- 2h appears to be legacy or auxiliary data.

---

## 10. Indicator State

indicators rows by timeframe:

| Timeframe | Rows | Tickers | Last timestamp |
|---|---:|---:|---|
| 30min | 27727 | 30 | 2026-07-20 11:30:00 |
| 1h | 18199 | 30 | 2026-07-20 11:00:00 |
| 2h | 8001 | 30 | 2026-07-20 10:00:00 |
| 4h | 4583 | 30 | 2026-07-20 08:00:00 |
| 1d | 274 | 30 | 2026-07-12 02:00:00 |

Observation:
- 1d indicators exist but only 274 rows.
- this is likely insufficient for long moving averages such as SMA 200.
- this may explain why no 1d signals were generated.

---

## 11. Signal State

Total signals:
- 42275

Signals by timeframe:

| Timeframe | Signals |
|---|---:|
| 30min | 23203 |
| 1h | 15246 |
| 4h | 3826 |

Signals by direction:

| Direction | Signals |
|---|---:|
| BUY | 17178 |
| SELL | 25097 |

Latest signal timestamp:
- 2026-07-20 11:30:00

Null counts in trading.signals:

| Field | Null rows |
|---|---:|
| macd | 0 |
| bb_position | 1 |
| volume_ratio | 0 |
| atr_pct | 0 |
| pattern_name | 0 |
| figi | 0 |

Observations:
- signals are enriched with pattern_name and figi.
- only one bb_position null exists.
- no 1d signals currently exist.

Top stocks:
- top_stocks_by_volume has 30 rows.
- latest report_date observed: 2026-07-22.

---

## 12. API Baseline

Confirmed baseline endpoints:

| Method | Path | Purpose |
|---|---|---|
| GET | /health | backend health |
| GET | /api/instruments | instrument list |
| GET | /api/candles | aggregated candles |
| GET | /api/signals | signal list |
| GET | /api/top-stocks-by-volume | top stocks by volume |

Important:
- frontend components may expect enhanced signals API features:
  - pagination;
  - date filter;
  - sorting;
  - pattern_name;
  - figi;
  - signal statistics endpoint.
- these enhancements may have been planned or partially applied manually.
- verify backend/app/api/market_data.py before relying on enhanced features.

---

## 13. Frontend Baseline

Frontend exists under:
- frontend/

Framework:
- React 18
- TypeScript
- Vite
- Tailwind CSS

Known components:
- SignalsPanel.tsx
- PatternStatsPanel.tsx
- SignalDetailModal.tsx
- CandleChart.tsx
- TopStocksPanel.tsx
- InstrumentsPanel.tsx

Vite dev proxy:
- /api -> http://localhost:8000

Status:
- frontend source files exist;
- npm dependencies were installed successfully in previous diagnostics;
- production build and runtime behavior are not verified by this baseline scan.

Recommended verification:
- npm run build
- npm run dev
- check /api proxy against running backend

---

## 14. Infrastructure Baseline

Docker Compose services:
- backend
- agent

Backend:
- builds from backend/Dockerfile
- exposes port 8000
- healthcheck uses /health
- connects to PostgreSQL using environment variables

Agent:
- builds from Dockerfile.agent
- mounts project root into /app
- uses OLLAMA_BASE_URL

Database:
- PostgreSQL is external or host-side.
- default Docker connection target is host.docker.internal.
- schema for analytics is trading.

Secrets:
- .env.example contains placeholders only.
- do not request or print secret values.
- do not commit .env.
- do not include tokens or passwords in reports.

---

## 15. Task Protocol

Development is task-based.

Each task should:
1. have a unique task ID;
2. be implemented as a bash script under scripts/;
3. produce artifacts under reports/<task_id>/;
4. produce report.json;
5. produce report.md;
6. produce log.txt.

Report statuses:
- success
- failed
- needs_human

Rules:
- do not edit code manually unless explicitly allowed;
- do not print secrets;
- do not run destructive commands;
- prefer idempotent operations;
- prefer small verifiable tasks;
- always check report.json before moving forward.

---

## 16. Agent-Specific Rules

Orchestrator:
- use this document as baseline context;
- do not assume files or endpoints not listed here;
- if unknown, create a read-only discovery task;
- do not propose production trading actions.

DevOps:
- execute only safe task scripts;
- preserve report artifacts;
- do not modify .env;
- do not delete database tables;
- rebuild backend image after backend code changes.

Backend Developer:
- use app.* imports, not src.*;
- preserve idempotent SQL;
- do not store secrets in code;
- verify API changes with tests or route checks.

Frontend Developer:
- use TypeScript strict mode;
- use /api proxy in dev;
- do not hardcode backend URL unless configurable;
- verify npm build before declaring success.

QA:
- check report.json status;
- run syntax checks;
- run tests where possible;
- verify API responses when relevant.

---

## 17. Known Issues and Unknowns

Confirmed issues:
1. No 1d signals exist.
2. 1d indicators are sparse: only 274 rows.
3. One signals row has bb_position null.
4. file_scan_report important_missing paths are false positives due actual module layout.
5. frontend build/runtime not verified by this baseline.
6. enhanced signals API features are not fully verified.
7. backend/app/api/signals.py appears legacy/unregistered.

Unknowns:
- whether frontend production build succeeds;
- whether frontend dev server correctly proxies to backend;
- whether current market_data.py includes pagination, date filters, sorting, stats;
- whether all tests pass;
- whether Docker backend image contains latest manual changes.

---

## 18. Recommended Next Tasks

Priority 1:
- verify frontend build;
- verify backend API compatibility with frontend;
- commit documentation and new scanner scripts if approved.

Priority 2:
- diagnose missing 1d signals;
- check 1d indicator depth;
- decide whether to load more daily history or adjust 1d patterns.

Priority 3:
- enhance or verify /api/signals pagination, sorting, date filters;
- add /api/signals/stats if not present;
- add pattern_name and figi to signals API response if missing.

Priority 4:
- design terminal schema for orders, positions, risk limits, audit logs;
- keep trading execution disabled until risk controls are implemented.

---

## 19. Machine-Readable Summary

project: trading-terminal
branch: main
phase: analytics and frontend visualization
trading_enabled: false
backend_framework: FastAPI
database: PostgreSQL
analytics_schema: trading
tables_count: 8
instruments_count: 4272
candles_30min_raw_count: 27960
candles_aggregated_count: 71195
indicators_count: 58784
signals_count: 42275
latest_signal_timestamp: 2026-07-20 11:30:00
top_stocks_count: 30
top_stocks_latest_report_date: 2026-07-22
frontend_present: true
frontend_build_verified: false
api_enhancements_verified: false
daily_signals_present: false
next_priority: verify frontend and API compatibility
EN_DOC

log "Writing Russian documentation"

cat > "${RU_DOC}" <<'RU_DOC'
# Trading Terminal - Контекст проекта

Сформировано: 2026-07-23
Сформировано задачей: task-036-docs-project-context
Источники:
- reports/task-035a-project-db-scan-fix/file_scan_report.md
- reports/task-035a-project-db-scan-fix/db_schema.md
- reports/task-035a-project-db-scan-fix/current_tree.txt

Этот документ описывает подтверждённое текущее состояние проекта.
Если какого-то факта здесь нет, его нужно отдельно проверить перед действиями.

---

## 1. Кратко о проекте

Trading Terminal - это платформа аналитики и алгоритмической торговли для MOEX с интеграцией T-Bank / Tinkoff Invest API.

Текущая стадия:
- сбор рыночных данных;
- агрегация свечей;
- расчёт индикаторов;
- генерация сигналов;
- отображение данных во фронтенде;
- торговля в production отключена.

Используется только sandbox / development режим.

---

## 2. Состояние репозитория

Текущая ветка:
- main

По current_tree.txt видно:
- изменён: agents/orchestrator/prompt.md
- не отслеживаются: scripts/db_schema_scanner.py
- не отслеживаются: scripts/task-034-project-rescan.sh
- не отслеживаются: scripts/task-035-project-db-scan.sh
- не отслеживаются: scripts/task-035a-project-db-scan-fix.sh

Сканирование файлов:
- всего файлов: 142
- Python-файлы: 43
- Markdown-файлы: 8
- bash-скрипты: 68
- frontend-файлы: TS, TSX, JS, CSS, HTML, JSON
- YAML-конфиги: 2

Метрики Python:
- строк Python-кода: 6460
- классов: 29
- функций верхнего уровня: 77
- методов: 77
- импортов: 164

---

## 3. Стек технологий

Backend:
- Python 3.12
- FastAPI
- uvicorn
- psycopg2-binary
- pandas
- asyncpg
- pydantic
- PyYAML

Frontend:
- React 18
- TypeScript
- Vite
- Tailwind CSS
- lightweight-charts

База данных:
- PostgreSQL
- аналитическая схема: trading
- будущая операционная схема: terminal

Инфраструктура:
- Docker Compose
- backend-сервис
- agent-сервис
- PostgreSQL доступен из Docker через host.docker.internal

Агентная система:
- Ollama
- qwen2.5-coder:7b
- config/agents.yaml

---

## 4. Общая архитектура

Основные части:

1. Backend API
   - FastAPI
   - endpoints для инструментов, свечей, сигналов, ТОП-акций
   - health endpoint

2. Аналитический pipeline
   - инструменты
   - 30-минутные свечи
   - агрегированные свечи
   - индикаторы
   - сигналы

3. База данных
   - схема trading
   - свечи, индикаторы, сигналы, инструменты, ТОП-акции

4. Frontend
   - React-приложение
   - таблица сигналов
   - статистика паттернов
   - ТОП-акции
   - инструменты
   - карточка сигнала со свечным графиком

5. Агентная система
   - orchestrator
   - devops executor
   - task-протокол разработки

---

## 5. Структура проекта

Основной источник:
- reports/task-035a-project-db-scan-fix/current_tree.txt

Ключевые пути:

Backend:
- backend/app/main.py
- backend/app/api/market_data.py
- backend/app/api/signals.py
- backend/app/analytics/indicators_manager.py
- backend/app/analytics/signal_engine.py
- backend/app/analytics/signal_generator.py
- backend/app/analytics/run_generate_signals.py
- backend/app/analytics/aggregate_candles.py
- backend/app/analytics/candles_aggregator.py
- backend/app/analytics/pipeline.py
- backend/app/analytics/top_stocks.py
- backend/app/analytics/patterns/base.py
- backend/app/analytics/patterns/trend.py
- backend/app/analytics/patterns/mean_reversion.py
- backend/app/analytics/patterns/breakout.py
- backend/app/analytics/patterns/volume.py
- backend/app/analytics/patterns/price_action.py
- backend/app/broker/data_loader.py
- backend/app/core/config_manager.py
- backend/app/db/db_manager.py
- backend/tests/

Frontend:
- frontend/package.json
- frontend/vite.config.js
- frontend/tsconfig.json
- frontend/tailwind.config.js
- frontend/postcss.config.js
- frontend/index.html
- frontend/src/main.tsx
- frontend/src/App.tsx
- frontend/src/api.ts
- frontend/src/types.ts
- frontend/src/components/SignalsPanel.tsx
- frontend/src/components/PatternStatsPanel.tsx
- frontend/src/components/SignalDetailModal.tsx
- frontend/src/components/CandleChart.tsx
- frontend/src/components/TopStocksPanel.tsx
- frontend/src/components/InstrumentsPanel.tsx

Документация:
- docs/agent-protocol.md
- docs/architecture/database.md
- docs/architecture/overview.md
- docs/domain/data-model.md
- docs/product/mvp.md
- docs/security/secrets.md
- docs/orchestrator/first-task.md

Конфиги:
- config/agents.yaml
- .env.example

Скрипты:
- scripts/task-*.sh
- scripts/targeted_project_scanner.py
- scripts/db_schema_scanner.py

---

## 6. Backend

Точка входа:
- backend/app/main.py

Подтверждённые baseline-endpoints:
- /health
- /api/instruments
- /api/candles
- /api/signals
- /api/top-stocks-by-volume

Важно:
- backend/app/api/signals.py существует, но похож на legacy-роутер.
- baseline main.py регистрирует market_data routes.
- перед включением или изменением signals.py нужно проверить, используется ли он.

Доступ к БД:
- backend/app/db/db_manager.py даёт синхронный DBManager.
- DBManager предназначен для аналитики, ETL и служебных задач.
- текущие API-обработчики используют синхронный доступ к БД через market_data.py.
- asyncpg есть в зависимостях и в check_external.py, но основной API пока не полностью async.

Конфигурация:
- backend/app/core/config_manager.py загружает настройки из окружения и YAML.
- пароль БД должен приходить только из переменных окружения.
- используются переменные:
  - TINVEST_TOKEN
  - TINVEST_ACC
  - PSTGRS_PWD
  - POSTGRES_HOST
  - POSTGRES_PORT
  - POSTGRES_USER
  - POSTGRES_DB
  - MARKET_DATA_DATABASE_URL
  - MARKET_DATA_SCHEMA

---

## 7. Аналитический pipeline

Логический поток данных:

instruments
  -> candles_30min_raw
    -> candles_aggregated
      -> indicators
        -> signals

Поток ТОП-акций:

candles / instruments
  -> top_stocks_by_volume

Поток генерации сигналов:

indicators
  -> SignalEngine
    -> паттерны
      -> trading.signals

Файлы паттернов:
- backend/app/analytics/patterns/base.py
- backend/app/analytics/patterns/trend.py
- backend/app/analytics/patterns/mean_reversion.py
- backend/app/analytics/patterns/breakout.py
- backend/app/analytics/patterns/volume.py
- backend/app/analytics/patterns/price_action.py

Движок:
- backend/app/analytics/signal_engine.py

Генератор сигналов:
- backend/app/analytics/signal_generator.py

Известные паттерны:
- Trend_SMA_Alignment
- MR_RSI_Reversal
- BO_BB_Squeeze
- VOL_Spike
- VOL_Low_Pullback
- PA_Hammer
- PA_HangingMan
- PA_Engulfing
- PA_ThreeWhiteSoldiers
- PA_ThreeBlackCrows

Важная поправка по сканеру:
- file_scan_report.md считает отсутствующими:
  - backend/app/analytics/signal_patterns/engine.py
  - backend/app/analytics/signal_patterns/base.py
- фактические пути в проекте:
  - backend/app/analytics/signal_engine.py
  - backend/app/analytics/patterns/base.py
- не нужно создавать signal_patterns/engine.py или signal_patterns/base.py, если нет осознанного рефакторинга структуры.

---

## 8. Модель данных: схема trading

Время сканирования:
- 2026-07-23T08:59:15

Схема:
- trading

Таблицы:

| Таблица | Строк | Колонок | Назначение |
|---|---:|---:|---|
| candles | 3326 | 10 | legacy / интервальные свечи, в выборке видны месячные |
| candles_30min_raw | 27960 | 9 | исходные 30-минутные свечи |
| candles_aggregated | 71195 | 10 | агрегированные свечи по таймфреймам |
| indicators | 58784 | 33 | рассчитанные технические индикаторы |
| instruments | 4272 | 15 | справочник инструментов |
| signals | 42275 | 19 | сгенерированные торговые сигналы |
| signals_backup_task_031e | 6648 | 19 | резервная таблица, приложением не используется |
| top_stocks_by_volume | 30 | 12 | ТОП-акции по объёму |

---

## 9. Состояние свечей

candles_aggregated по таймфреймам:

| Таймфрейм | Строк |
|---|---:|
| 30min | 35339 |
| 1h | 18769 |
| 2h | 8571 |
| 4h | 6008 |
| 1d | 1946 |
| 1w | 389 |
| 1M | 173 |

Наблюдение:
- в candles_aggregated есть 2h.
- текущая генерация сигналов использовала 30min, 1h, 4h, 1d.
- 2h выглядит как вспомогательный или legacy-таймфрейм.

---

## 10. Состояние индикаторов

indicators по таймфреймам:

| Таймфрейм | Строк | Тикеров | Последний timestamp |
|---|---:|---:|---|
| 30min | 27727 | 30 | 2026-07-20 11:30:00 |
| 1h | 18199 | 30 | 2026-07-20 11:00:00 |
| 2h | 8001 | 30 | 2026-07-20 10:00:00 |
| 4h | 4583 | 30 | 2026-07-20 08:00:00 |
| 1d | 274 | 30 | 2026-07-12 02:00:00 |

Наблюдение:
- 1d индикаторы есть, но всего 274 строки.
- этого, вероятно, недостаточно для длинных скользящих, например SMA 200.
- это может объяснять отсутствие 1d сигналов.

---

## 11. Состояние сигналов

Всего сигналов:
- 42275

Сигналы по таймфреймам:

| Таймфрейм | Сигналов |
|---|---:|
| 30min | 23203 |
| 1h | 15246 |
| 4h | 3826 |

Сигналы по направлению:

| Направление | Сигналов |
|---|---:|
| BUY | 17178 |
| SELL | 25097 |

Последний timestamp сигнала:
- 2026-07-20 11:30:00

NULL-значения в trading.signals:

| Поле | NULL-строк |
|---|---:|
| macd | 0 |
| bb_position | 1 |
| volume_ratio | 0 |
| atr_pct | 0 |
| pattern_name | 0 |
| figi | 0 |

Наблюдения:
- сигналы обогащены pattern_name и figi.
- есть только один bb_position null.
- 1d сигналов сейчас нет.

ТОП-акции:
- top_stocks_by_volume содержит 30 строк.
- последняя наблюдаемая report_date: 2026-07-22.

---

## 12. API

Подтверждённые baseline-endpoints:

| Метод | Путь | Назначение |
|---|---|---|
| GET | /health | проверка backend |
| GET | /api/instruments | список инструментов |
| GET | /api/candles | агрегированные свечи |
| GET | /api/signals | список сигналов |
| GET | /api/top-stocks-by-volume | ТОП-акции по объёму |

Важно:
- frontend-компоненты могут ожидать расширенные возможности API:
  - пагинация;
  - фильтр по дате;
  - сортировка;
  - pattern_name;
  - figi;
  - endpoint статистики по сигналам.
- эти улучшения могли быть запланированы или частично добавлены вручную.
- перед использованием нужно проверить backend/app/api/market_data.py.

---

## 13. Frontend

Frontend находится в:
- frontend/

Используется:
- React 18
- TypeScript
- Vite
- Tailwind CSS

Известные компоненты:
- SignalsPanel.tsx
- PatternStatsPanel.tsx
- SignalDetailModal.tsx
- CandleChart.tsx
- TopStocksPanel.tsx
- InstrumentsPanel.tsx

Vite dev proxy:
- /api -> http://localhost:8000

Статус:
- исходники frontend существуют;
- npm-зависимы ранее устанавливались успешно;
- production build и runtime не подтверждены этим сканированием.

Рекомендуемая проверка:
- npm run build
- npm run dev
- проверить /api proxy до запущенного backend

---

## 14. Инфраструктура

Docker Compose сервисы:
- backend
- agent

Backend:
- собирается из backend/Dockerfile
- открывает порт 8000
- healthcheck использует /health
- подключается к PostgreSQL через переменные окружения

Agent:
- собирается из Dockerfile.agent
- монтирует корень проекта в /app
- использует OLLAMA_BASE_URL

База данных:
- PostgreSQL внешний или хостовый.
- по умолчанию из Docker используется host.docker.internal.
- аналитическая схема: trading.

Секреты:
- .env.example содержит только плейсхолдеры.
- нельзя запрашивать и печатать секретные значения.
- нельзя коммитить .env.
- нельзя включать токены и пароли в отчёты.

---

## 15. Протокол задач

Разработка идёт через задачи.

Каждая задача должна:
1. иметь уникальный task ID;
2. быть bash-скриптом в scripts/;
3. создавать артефакты в reports/<task_id>/;
4. создавать report.json;
5. создавать report.md;
6. создавать log.txt.

Статусы отчётов:
- success
- failed
- needs_human

Правила:
- не редактировать код вручную, если это явно не разрешено;
- не печатать секреты;
- не запускать destructive-команды;
- предпочитать идемпотентные операции;
- предпочитать маленькие проверяемые задачи;
- всегда смотреть report.json перед следующим шагом.

---

## 16. Правила для агентов

Orchestrator:
- использовать этот документ как базовый контекст;
- не предполагать файлы и endpoints, которых здесь нет;
- если данных нет, создавать read-only discovery задачу;
- не предлагать production trading.

DevOps:
- выполнять только безопасные task-скрипты;
- сохранять отчёты;
- не менять .env;
- не удалять таблицы БД;
- пересобирать backend image после изменений backend-кода.

Backend Developer:
- использовать app.* импорты, не src.*;
- сохранять идемпотентный SQL;
- не хранить секреты в коде;
- проверять изменения API тестами или route checks.

Frontend Developer:
- использовать TypeScript strict mode;
- использовать /api proxy в dev;
- не хардкодить backend URL без конфигурации;
- проверять npm build перед объявлением успеха.

QA:
- проверять статус report.json;
- запускать syntax checks;
- запускать тесты, где возможно;
- проверять API responses, если задача касается API.

---

## 17. Известные проблемы и неизвестное

Подтверждённые проблемы:
1. Нет 1d сигналов.
2. 1d индикаторов мало: всего 274 строки.
3. Одна строка сигналов имеет bb_position null.
4. important_missing в file_scan_report - ложное срабатывание из-за фактической структуры модулей.
5. frontend build/runtime не проверены этим baseline.
6. расширенный signals API не подтверждён.
7. backend/app/api/signals.py похож на legacy/unregistered.

Неизвестно:
- собирается ли frontend production build;
- корректно ли frontend dev server проксирует /api;
- есть ли в текущем market_data.py пагинация, фильтры по дате, сортировка и статистика;
- проходят ли все тесты;
- содержит ли Docker backend image последние ручные изменения.

---

## 18. Рекомендуемые следующие шаги

Приоритет 1:
- проверить frontend build;
- проверить совместимость backend API и frontend;
- закоммитить документацию и новые сканеры, если одобряется.

Приоритет 2:
- диагностировать отсутствие 1d сигналов;
- проверить глубину 1d индикаторов;
- решить, нужно ли загружать больше дневной истории или менять 1d паттерны.

Приоритет 3:
- проверить или добавить /api/signals пагинацию, сортировку, фильтры по дате;
- добавить /api/signals/stats, если его нет;
- убедиться, что pattern_name и figi отдаются в signals API.

Приоритет 4:
- спроектировать terminal schema для orders, positions, risk limits, audit logs;
- не включать торговлю, пока не реализованы risk controls.

---

## 19. Краткая сводка

проект: trading-terminal
ветка: main
фаза: аналитика и визуализация
торговля включена: нет
backend: FastAPI
база данных: PostgreSQL
аналитическая схема: trading
таблиц: 8
instruments: 4272
candles_30min_raw: 27960
candles_aggregated: 71195
indicators: 58784
signals: 42275
последний сигнал: 2026-07-20 11:30:00
top_stocks: 30
top_stocks report_date: 2026-07-22
frontend: есть
frontend build проверен: нет
API enhancements проверены: нет
1d сигналы: нет
следующий приоритет: проверить frontend и совместимость API
RU_DOC

FINISHED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "${REPORT_JSON}" <<JSON
{
  "task_id": "${TASK_ID}",
  "status": "success",
  "stage": "docs_created",
  "started_at": "${STARTED_AT}",
  "finished_at": "${FINISHED_AT}",
  "docs": [
    "${EN_DOC}",
    "${RU_DOC}"
  ],
  "source_reports": [
    "reports/task-035a-project-db-scan-fix/file_scan_report.md",
    "reports/task-035a-project-db-scan-fix/db_schema.md",
    "reports/task-035a-project-db-scan-fix/current_tree.txt"
  ],
  "next_action": "Review docs/agents/project-context.md and docs/project-context.ru.md"
}
JSON

cat > "${REPORT_MD}" <<MD
# ${TASK_ID}

Status: success
Stage: docs_created
Started: ${STARTED_AT}
Finished: ${FINISHED_AT}

Created docs:

- ${EN_DOC}
- ${RU_DOC}

Source reports:

- reports/task-035a-project-db-scan-fix/file_scan_report.md
- reports/task-035a-project-db-scan-fix/db_schema.md
- reports/task-035a-project-db-scan-fix/current_tree.txt

Next action:

Review docs/agents/project-context.md and docs/project-context.ru.md
MD

log "English doc: ${EN_DOC}"
log "Russian doc: ${RU_DOC}"
log "Report JSON: ${REPORT_JSON}"
log "Done"

exit 0
